Add package information to allow the stubs to be installed by uv
Otherwise the installation fails because:

```
error: Multiple top-level packages discovered in a flat-layout: ['codegen', 'kubernetes', 'kubernetes_ext'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.
```

Add setuptools bumf